version: '3'

services:
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    working_dir: /www
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/www
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /www
    container_name: api
    volumes:
      - ./:/www
    networks:
      - internal

networks:
  internal:
    driver: bridge
